spring:
  application:
    name: eventhub-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/eventhub}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  mail:
    host: smtp.mail.ru
    port: 465
    username: ${EMAIL_LOGIN:example@mail.ru}
    password: ${MAIL_APPLICATION_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
server:
  port: 8080
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: /api/event-hub
  api-docs:
    path: /v3/api-docs

app:
  registration:
    cleanupJob:
      cron: 0 0 * * * *
      zone: Europe/Moscow
    confirmationCodeExpirationMinutes: 5
  storage:
    cleanupJob:
      delayMinutes: 60
    bucket:
      name: eventhub
      nonConfirmedExpiryMinutes: 15
    user: miniouser
    password: miniopassword
    hostPort: "minio:9000"

management:
  endpoint:
    health:
      probes:
        enabled: true
      access: unrestricted
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"