apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventhub-backend-deployment
  labels:
    {{- include "eventhub-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.eventhubBackendDeploy.replicas }}
  selector:
    matchLabels:
      {{- include "eventhub-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations: {}
      labels:
        {{- include "eventhub-backend.labels" . | nindent 8 }}
    spec:
      hostAliases:
        - ip: "192.168.100.101"
          hostnames:
            - "eventhub-backend.ru"
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.eventhubBackendDeploy.container.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.eventhubBackendDeploy.container.image.repository }}:{{ .Values.eventhubBackendDeploy.container.image.tag }}"
          env:
          - name: DB_URL
            value: jdbc:postgresql://eventhub-backend-postgresql:5432/{{ .Values.postgresql.auth.database }}
          - name: DB_USERNAME
            value: {{ .Values.postgresql.auth.username | quote }}
          - name: DB_PASSWORD
            value: {{ .Values.postgresql.auth.password | quote }}
          - name: EMAIL_LOGIN
            value: {{ .Values.eventhubBackendDeploy.appConfig.mail.login | quote }}
          - name: MAIL_APPLICATION_PASSWORD
            value: {{ .Values.eventhubBackendDeploy.appConfig.mail.password | quote }}
          - name: MINIO_USER
            value: {{ .Values.eventhubBackendDeploy.appConfig.storage.minio.user | quote }}
          - name: MINIO_PASSWORD
            value: {{ .Values.eventhubBackendDeploy.appConfig.storage.minio.password | quote }}
          - name: MINIO_URL_INTERNAL
            value: {{ .Values.eventhubBackendDeploy.appConfig.storage.minio.url.internal | quote }}
          - name: MINIO_URL_EXTERNAL
            value: {{ .Values.eventhubBackendDeploy.appConfig.storage.minio.url.external | quote }}
          - name: MINIO_BUCKET_NAME
            value: {{ .Values.eventhubBackendDeploy.appConfig.storage.minio.bucket.name | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.eventhubBackendDeploy.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.eventhubBackendDeploy.container.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: eventhub-backend-configmap
